paths:
  static: ''
  uploads: uploads
timezone: Europe/Rome
markdown:
  engine: commonmark
  options: {}
# Definisce dove si trovano le pagine del tuo sito da modificare
collections_config:
  pages:
    name: Pagine del Sito
    path: /
    output: true
    filter:
      base: strict
      globs:
        - "*.html"

# Specifica quali editor attivare (il visual editor serve per il drag&drop / inline)
_enabled_editors:
  - visual
  - content
  - source

# Configura il Visual Editor per i siti HTML statici
html_options:
  visual: true

